- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 300
  ignore_errors: True
  when: ansible_os_family  == "Debian"

- name: install required packages
  apt: name={{ item }} state=latest
  with_items:
    - runit
    - curl
  when: ansible_os_family  == "Debian"

- name: download
  get_url: dest="/tmp/apache-cassandra-{{ cassandra_version }}-bin.tar.gz" url="http://apache-mirror.rbc.ru/pub/apache/cassandra/{{ cassandra_version }}/apache-cassandra-{{ cassandra_version }}-bin.tar.gz"

- name: checksumming cassandra
  shell: echo "{{ cassandra_version_sha1 }} /tmp/apache-cassandra-{{ cassandra_version }}-bin.tar.gz" | sha1sum -c -
  when: cassandra_version not in ["latest", "stable"]

- name: create all the necessary dirs
  file: path=/{{ item }} state=directory
  with_items:
    - sv/cassandra/log
    - "{{ cassandra_path_install }}"
    - "{{ cassandra_path_logs }}"
    - "{{ cassandra_path_hints }}"
    - "{{ cassandra_path_caches }}"

- name: create all the necessary dirs
  file: path=/{{ item }} state=directory
  with_items: "{{ cassandra_path_data }}"

- name: unpack
  unarchive: src="/tmp/apache-cassandra-{{ cassandra_version }}-bin.tar.gz" dest="{{ cassandra_path_install }}" copy=no

- name: remove archive
  file: path="/tmp/apache-cassandra-{{ cassandra_version }}-bin.tar.gz" state=absent

- name: remove old install
  file: path="{{ cassandra_path_install }}/cassandra" state=absent

- name: update symlink
  file: src="apache-cassandra-{{ cassandra_version }}" dest="{{ cassandra_path_install }}/cassandra" state=link

- name: put symlink for cqlsh in /usr/local/bin
  file: src="{{ cassandra_path_install }}/cassandra/bin/cqlsh" dest="/usr/local/bin/cqlsh" state=link
  when: not cassandra_ommit_bin_link

- name: create user
  user: name="{{ cassandra_user }}" comment="cassandra run user" home="{{ cassandra_path_install }}" createhome=no

- name: make all the file RO
  file: path="{{ cassandra_path_install }}/apache-cassandra-{{ cassandra_version }}" owner="{{ cassandra_user }}" group='root' mode="a-w" recurse=yes
  tags: test

- name: make some dirs RW
  file: path="{{ item }}" owner="{{ cassandra_user }}" group='root' mode="u+w" recurse=yes
  with_items:
    - "{{ cassandra_path_logs }}"
    - "{{ cassandra_path_hints }}"
    - "{{ cassandra_path_caches }}"

- name: make some dirs RW
  file: path="{{ item }}" owner="{{ cassandra_user }}" group='root' mode="u+w" recurse=yes
  with_items: "{{ cassandra_path_data }}"
